### ISSUE TITLE
Problem with algorith to display cards on backend Customer and Payment

### ISSUE THREAD

**Issue by williamjean** [hipay/hipay-fullservice-sdk-magento2#107]
Hello,

I have seen an issue on the version 1.1.5.
On this file HiPay\FullserviceMagento\Model\ResourceModel\Card\Collection for the method onlyValid()
Instead of to have this code : 
`if($card->getCcExpYear() == $currentYear && $currentMonth < $card->getCcExpMonth())`

it should be: 
`if($card->getCcExpYear() == $currentYear && $card->getCcExpMonth() < $currentMonth)` 

Regards,

**Comment by etiennelandais** [comment]
Hello ! 

Thank you for bringing this issues !

This has been fixed in the last release [#1.2.1](https://github.com/hipay/hipay-fullservice-sdk-magento2/releases/tag/1.2.1)

Etienne
