### ISSUE TITLE
Error for declined payment.

### ISSUE THREAD

**Issue by nikolay-malukhin** [hipay/hipay-fullservice-sdk-magento2#114]
Magento ver. 2.2.3
Module version: 1.2.2

Step to reproduce:

1. Create new order.
2. Try to pay with test card 

4111113333333333	
VISA      
toujours refusée
(Development mode)

3. We have next error.

![screenshot from 2018-09-03 16-39-07](https://user-images.githubusercontent.com/4183592/44992601-00e99d00-af98-11e8-9898-9dc9b9665e9d.png)

**Comment by etiennelandais** [comment]
Hi !
Thank you for briging this issue ! 

Can you try to update your module to the latest release (1.3.1) and tells us if you still reproduce this bug ?

Thanks

**Comment by etiennelandais** [comment]
Hello !

we fixed this issue in our latest release :
https://github.com/hipay/hipay-fullservice-sdk-magento2/releases/tag/1.3.2

**Comment by nikolay-malukhin** [comment]
With version 1.3.1, nothing has changed.

![screenshot from 2018-09-12 14-34-07](https://user-images.githubusercontent.com/4183592/45425226-02eae480-b699-11e8-9526-b1f0d527bde3.png)

**Comment by etiennelandais** [comment]
Hello 
the latest release is 1.3.2 
https://github.com/hipay/hipay-fullservice-sdk-magento2/releases/tag/1.3.2

**Comment by nikolay-malukhin** [comment]
@etiennelandais  Thanks!
