### ISSUE TITLE
Api username can't be emtpy and must be a string

### ISSUE THREAD

**Issue by Axel29** [hipay/hipay-fullservice-sdk-magento2#115]
### Description du bug

Le fichier var/log/system.log se remplit énormément à chaque passage au checkout avec l'erreur suivante :

> main.CRITICAL: Api username can't be emtpy and must be a string [] []

### Pré-conditions

1. Magento: 2.2.3
2. PHP: 7.1
3. Module HiPay version 1.3.2

### Étapes pour reproduire

1. Créer plusieurs websites
1. Se connecter au back-office Magento 2
1. Aller dans Boutiques -> Paramètres -> Configurations -> Ventes -> HiPay Enterprise
1. Changer la vue pour se placer **au niveau website**
1. Renseigner les identifiants API **au niveau website**
1. Sauvegarder la configuration
1. Accéder au checkout
1. Ouvrir le fichier var/log/system.log

### Résultat attendu

1. Aucune erreur ne devrait apparaître dans le fichier de log

### Résultat obtenu

1. Une erreur apparaît en masse :

> main.CRITICAL: Api username can't be emtpy and must be a string [] []

Après avoir tenté de modifier la configuration et renseigner les identifiants au niveau global, nous obtenons toujours le même log qui fait que le fichier system.log grossit énormément.

**Comment by jprotin** [comment]
Bonjour @Axel29 

Merci beaucoup pour votre retour, nous allons verifier ceci sur nos environnements de tests et nous vous tiendrons au courant rapidement.

Nous sommes aujourd'hui sur une version 1.4.0, vous avez 4 versions de retard. Pouvez-vous nous vous mettre à jour et nous dire en parallèle de nos tests si vous rencontrez toujours le problème ?

Merci beaucoup

Johan

**Comment by Axel29** [comment]
Bonjour @jprotin,

Je clos ce ticket car effectivement sur les nouvelles versions du module le log n'apparaît plus.

Merci,

Axel
