### ISSUE TITLE
Inscription - Validation cassée

### ISSUE THREAD

**Issue by Axel29** [hipay/hipay-fullservice-sdk-magento2#117]
### Pré-conditions

1. Magento: 2.2.3
2. PHP: 7.1

### Étapes pour reproduire

1. Installer Magento 2.2.3
2. Installer le module HiPay_FullService avec la dernière version (à date 1.4.2)
3. Mettre à jours la base de données (`php bin/magento setup:upgrade`)
3. Purger les fichiers statiques (`rm -rf pub/static/frontend/Magento/`)
4. Purger le cache magento (`php bin/magento cache:flush`)
5. Accéder à la page de création de compte client (/customer/account/create)
6. Valider le formulaire sans remplir aucun champ

### Résultat attendu

1. Des messages d'erreurs doivent apparaître sous chaque champ requis
2. L'envoie du formulaire est bloqué

### Résultat obtenu

1. Le formulaire s'envoie malgré tout
2. Aucune validation n'est faite
3. Au rechargement de la page, un message d'erreur apparaît à propos du champ mot de passe uniquement.

### Informations complémentaires

Le problème semble venir de la surcharge du JS "validation" dans le fichier "hipay/hipay-fullservice-sdk-magento2/view/frontend/web/js/validation.js", déclaré dans le fichier hipay/hipay-fullservice-sdk-magento2/view/frontend/requirejs-config.js :

```json
var config = {
    "map": {
        "*": {
            "card": "HiPay_FullserviceMagento/card",
            "validation": "HiPay_FullserviceMagento/js/validation"
        }
    },
    "config": {
        "mixins": {
            "Magento_Tax/js/view/checkout/summary/grand-total": {
                "HiPay_FullserviceMagento/js/grand-total-mixin": true
            }
        }
    }
};
```

**Comment by Axel29** [comment]
Après avoir débuggé de mon côté, j'ai fini par trouver l'erreur.

Elle se situait bien dans le fichier validation.js. Au lieu de déclarer le début du fichier via un `define([...], function () { ... });`, vous avez utilisé un `require([...], function () { ... });`.

Voici le bon code à utiliser :

```javascript
define([
    'jquery',
    'mage/validation',
    'Magento_Payment/js/model/credit-card-validation/cvv-validator',
    'Magento_Payment/js/model/credit-card-validation/credit-card-data'
], function($,validation,cvvValidator,creditCardData){
    $.validator.addMethod(
        'validate-cvv-hipay', function (value, element) {
            if (creditCardData.creditCard.type != 'MI' || value != '' ) {
                var maxLength = creditCardData.creditCard ? creditCardData.creditCard.code.size : 3;
                return cvvValidator(value, maxLength).isValid;
            }
            return true;
        }, $.mage.__('Please enter a valid credit card verification number.'));

});
```

**Comment by legithubdeaymeric** [comment]
Merci @Axel29 pour le retour et la PR.

On l'intègre dans la prochaine release !
