### ISSUE TITLE
Undefined property: HiPay\FullserviceMagento\Helper\Data::$_ruleFactory

### ISSUE THREAD

**Issue by ari-beautysuccess** [hipay/hipay-fullservice-sdk-magento2#119]
Hi,

There is a name mismatching between the property $ruleFactory and its usage:

> {"message":"Erreur de requete pour la nouvelle transaction : Notice: **Undefined property: HiPay\\FullserviceMagento\\Helper\\Data::$_ruleFactory** in [...]/vendor\/hipay\/hipay-fullservice-sdk-magento2\/Helper\/Data.php on line 84."}

```
    /**
     *
     * @var \HiPay\FullserviceMagento\Model\RuleFactory $_ruleFactory
     */
    protected $ruleFactory;

    public function is3dSecure($use3dSecure, $config3dsRules, $quote = null)
    {
        [...]
                    $rule = $this->_ruleFactory->create();
```

Regards

**Comment by etiennelandais** [comment]
Hello,

Thank you for briging this issue.
It has been fix in the latest release: 
https://github.com/hipay/hipay-fullservice-sdk-magento2/releases/tag/1.6.1

regards
