### ISSUE TITLE
LocalizedException not found

### ISSUE THREAD

**Issue by ramzy11** [hipay/hipay-fullservice-sdk-magento2#120]
Hello,

There is a fatal error on LocalizedException call. 

`
Fatal error: Uncaught Error: Class 'HiPay\FullserviceMagento\Observer\LocalizedException' not found in vendor/hipay/hipay-fullservice-sdk-magento2/Observer/CheckHttpSignatureObserver.php:104
`

Missing \Magento\Framework\Exception\LocalizedException.

**Comment by etiennelandais** [comment]
Hello

this issue has been fixed in the latest release
https://github.com/hipay/hipay-fullservice-sdk-magento2/releases/tag/1.7.1

thank you for briging this issue

Regards
