### ISSUE TITLE
Request validation failed for action

### ISSUE THREAD

**Issue by ramzy11** [hipay/hipay-fullservice-sdk-magento2#121]
Hi,

We have an error on notification url after upgrading to Magento 2.3.2 version :

Nginx log : 
`"POST /hipay/notify/index HTTP/1.1" 302 30 "-" "Allopass" "-"`

Error log :
`Request validation failed for action "HiPay\FullserviceMagento\Controller\Notify\Index\Interceptor"`

Thanks.

**Comment by ramzy11** [comment]
Hi,

The solution : 
- Must `implements CsrfAwareActionInterface` on Notify/Index controller 
- add the two functions 

```php
/**
 * @inheritDoc
 */
public function createCsrfValidationException(
    RequestInterface $request
): ?InvalidRequestException {
    return null;
}

/**
 * @inheritDoc
 */
public function validateForCsrf(RequestInterface $request): ?bool
{
    return true;
}
```

**Comment by legithubdeaymeric** [comment]
Hi, 

Which version of our module do you use?

Normally, it's manage by a fix:
https://github.com/hipay/hipay-fullservice-sdk-magento2/commit/1eb0951938f2cc0043c4714c548c3c63b84e83dc#diff-085299f578f3ccc7f9c17d0d1295166bR55

**Comment by ramzy11** [comment]
Hi,

I'm using the 1.6.1 version.

Thank you in advance

**Comment by etiennelandais** [comment]
Hi,

This issue has been fixed in the latest release 

https://github.com/hipay/hipay-fullservice-sdk-magento2/releases/tag/1.7.2

Regards
