### ISSUE TITLE
1.7.0 errors

### ISSUE THREAD

**Issue by mrtsmax** [hipay/hipay-fullservice-sdk-magento2#122]
Hi,

I have several errors due to the new version 1.7.0 :
- magento version : 2.3.1
- hipay module : "hipay/hipay-fullservice-sdk-magento2" at master branch (1.7.0 tag)

Errors when setup:di:compile : 
1/ `PHP Fatal error: Declaration of HiPay\FullserviceMagento\Model\Config::setApiUsername($apiUsername) must be compatible with HiPay\Fullservice\HTTP\Configuration\ConfigurationInterface::setApiUsername(string $apiUsername) in vendor/hipay/hipay-fullservice-sdk-magento2/Model/Config.php on line 37`

➡️  Resolved by cast parameters of this functions :
string :
setApiHTTPHeaderAccept 
setApiPassword 
setApiUsername 
setApiEnv

array :
setProxy

int : 
setCurlConnectTimeout 
setCurlTimeoutstring

2/ `PHP Fatal error: Class HiPay\FullserviceMagento\Model\Config contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (HiPay\Fullservice\HTTP\Configuration\ConfigurationInterface::setCurlTimeout) in vendor/hipay/hipay-fullservice-sdk-magento2/Model/Config.php on line 37`

**Comment by jprotin** [comment]
Hi @mrtsmax 
thank you for your feedback.
We quickly fix it.

Best.

**Comment by etiennelandais** [comment]
Hello 

those issues have been fixed in the latest release 
https://github.com/hipay/hipay-fullservice-sdk-magento2/releases/tag/1.7.1

thank you for briging those issues 

Regards
