### ISSUE TITLE
Multishipping

### ISSUE THREAD

**Issue by usr443** [hipay/hipay-fullservice-sdk-magento2#123]
Hello,

I noticed that the payment methods provided by this module don't show up on the frontend when multishipping is enabled.

That's because `allow_multiple_address` is set to `0` in the `payment.xml` file (for all payment methods).

Of course, overriding it to `1` isn't enough. The payment methods get displayed on the billing page, but they don't ask for the payment information.

So, is there any way to make it work with the multishipping checkout?

**Comment by jprotin** [comment]
Hi @usr443 

I'm sorry, the multiple address is not available in our extension.
Our product owner analyse this feature for a new release available certainly this year. But i do not have a dealine in our roadmap.

Thank you !

All the best.
