### ISSUE TITLE
GraphQl support for PWA ?

### ISSUE THREAD

**Issue by angelflo** [hipay/hipay-fullservice-sdk-magento2#125]
Hi,
Did you plan to implement GraphQL in your extension in next release in order to use your payment solution in PWA project ?
If yes, do you have an estimated release date for this ?
Thanks a lot

**Comment by FrancescFerreSanchez** [comment]
Hi @angelflo 

We are not planning on adding this feature sooner than Q4 2020.
Are you already using PWA or planning on adding it to your store ?

Thanks
