### ISSUE TITLE
2.4 Install not works PHP 7.4

### ISSUE THREAD

**Issue by brmor-group-label** [hipay/hipay-fullservice-sdk-magento2#130]
Hi,

It's impossible to install your last version (1.11.0) we have an error about deprecated functionnality when setup:upgrade.

Deprecated Functionality: Unparenthesized `a ? b : c ? d : e` is deprecated Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /app/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Config.php on line 144

**Comment by legithubdeaymeric** [comment]
Hi, 

Release with fix for that will be available this afternoon !

**Comment by nverhoye** [comment]
Hello, same issue here when i run 
bin/magento s:d:c     
                    
Compilation was started.
Repositories code generation... 1/9 [===>------------------------]  11% 1 sec 133.0 MiB
In ErrorHandler.php line 61:
                                                                                                                                                                             
  Deprecated Functionality: Unparenthesized `a ?: b ? c : d` is deprecated. Use either `(a ?: b) ? c : d` or `a ?: (b ? c : d)` in /var/www/html/vendor/hipay/hipay-fullser  
  vice-sdk-magento2/Model/Request/PaymentMethod/CardToken.php on line 39    

Version used 1.13.6 on php 7.4 and magento 2.4.3-p1

**Comment by BeardTech** [comment]
@nverhoye  i think the 1.13.8 release fix this :)

**Comment by legithubdeaymeric** [comment]
https://github.com/hipay/hipay-fullservice-sdk-magento2/releases/tag/1.13.8
