### ISSUE TITLE
Si la méthode de paiement Enterprise Credit Card Hosted Fields est activée, les autres modes ne fonctionnent pas

### ISSUE THREAD

**Issue by walkwizus** [hipay/hipay-fullservice-sdk-magento2#132]
Comme dit dans le titre, si cette méthode de paiement est activée, alors les autres modes de paiement ne fonctionnent plus (Checkmo / Hipay Paypal etc...).

Dans le fichier: HiPay_FullserviceMagento/web/js/view/payment/method-renderer/hipay-hosted-fields.js il y a un appel explicite à la méthode isPlaceOrderActionAllowed() dans l'initialize ce qui a pour action de désactiver les boutons de validation des autres modes de paiement.

Il y a également un autre souci avec l'évènement onChange sur les champs du formulaire de saisie de CB. Si un numéro de CB erroné est saisie alors les autres moyens de paiement seront désactivés. Il faudrait rappeler la méthode isPlaceOrderActionAllowed(true) dans le cas ou le formulaire est vidé.

**Comment by legithubdeaymeric** [comment]
@walkwizus 

Thanks !
Fix here => https://github.com/hipay/hipay-fullservice-sdk-magento2/releases/tag/1.13.0
