### ISSUE TITLE
Erreur de log lors d'une notification

### ISSUE THREAD

**Issue by walkwizus** [hipay/hipay-fullservice-sdk-magento2#134]
Bonjour,

Si une notification lève une exception, le logger renvoie une erreur (HiPay\FullserviceMagento\Controller\Notify\Index L82) car la méthode warn n'existe pas. Ceci est du a une modification de l'injection de dépendance sur Magento 2.4: 
https://github.com/magento/magento2/commit/28d2a5bf4bd3588dfe6f0d3d0fc2036c6fcc9ef7#diff-12072a309c8288501e47bf04037c9330e474f560da6e9fac8aaf8018330aa19a qui au lieu de passer la classe Monolog passe maintenant la classe LoggerProxy. Il faudrait donc renommer la méthode warn en warning comme dit dans la documentation: https://devdocs.magento.com/guides/v2.4/config-guide/log/log-magento.html

**Comment by legithubdeaymeric** [comment]
@walkwizus 

Thanks !
Fix on https://github.com/hipay/hipay-fullservice-sdk-magento2/releases/tag/1.13.0
