### ISSUE TITLE
Mapping Catégories ne fonctionne pas en multi website

### ISSUE THREAD

**Issue by brmor-group-label** [hipay/hipay-fullservice-sdk-magento2#135]
**Pré-conditions**
Magento >= 2.4.1p1
PHP 7.4
Module HiPay installé (hipay/hipay-fullservice-sdk-magento2) version : 1.13.1
Multi Website avec Root Category différentes

**Étapes pour reproduire**
Se rendre dans le BO puis dans Hipay Enterprise / Mapping Categories

**Résultat actuel**
Seul les catégories du store par défaut sont visibles

**Résultat attendu**
Que l'ensemble des catégories puissent être mappées.

**Comment by BeardTech** [comment]
see change log https://github.com/hipay/hipay-fullservice-sdk-magento2/releases/tag/1.13.2 some news about category mapping

**Comment by legithubdeaymeric** [comment]
@brmor-group-label 

Yep, thanks for you issue, it's fixed now.
