### ISSUE TITLE
Problème de paiement avec Oney

### ISSUE THREAD

**Issue by walkwizus** [hipay/hipay-fullservice-sdk-magento2#136]
Bonjour,

Nous avons un souci sur l'implémentation d'Oney avec un produit contenant des options personnalisables.

Quand le panier est envoyé à Oney et que le produit contient des options personnalisables, il est impossible de charger 
le produit via un productRepository car le sku du produit est suffixé du SKU de l'option personnalisable, cela lève donc
une exception.

L'erreur se situe ici: 

https://github.com/hipay/hipay-fullservice-sdk-magento2/blob/master/Model/Request/CommonRequest.php#L199

Il ne faut pas prendre le SKU de l'objet OrderItem mais le SKU du produit.

**Comment by legithubdeaymeric** [comment]
Bonjour @walkwizus 

C'est fix dans la dernière release.
Merci pour votre retour.
