### ISSUE TITLE
Store credit not refunded to customer when order is cancelled by cron (Magento Commerce)

### ISSUE THREAD

**Issue by AymericJoubert** [hipay/hipay-fullservice-sdk-magento2#141]
**Preconditions :**
- Magento commerce
- Add a store credit to customer
- Create an order an use the store credit, pay the remaining amount with credit card
- Fail/stop the payment

**Bug :** 
The cron "CleanPendingOrders" with cancel the order, but will not refund store credit to customer.

**Context :** 
There is an event on order cancellation in magento commerce to refund store credit, but there is this condition a the beginning : 
```
if (!$order->getCustomerId() || !$order->getBaseCustomerBalanceAmount()) {
    return $this;
}
```
Store credit is not refunded because customer_id is not loaded within the order collection.

**Fix :**
Simply add 'customer_id' to the order collection selected fields in CleanPendingOrders and the process works well.

**Comment by pi-ecommerce** [comment]
Fixed in 1.14.3

Thanks
