### ISSUE TITLE
error when compile di

### ISSUE THREAD

**Issue by EspertoMagento** [hipay/hipay-fullservice-sdk-magento2#142]
Deprecated Functionality: Unparenthesized `a ?: b ? c : d` is deprecated.  
Use either `(a ?: b) ? c : d` or `a ?: (b ? c : d)` in /htdocs/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Request/PaymentMe  
  thod/CardToken.php on line 39

**Comment by BeardTech** [comment]
it's a know issue that i've been reported in #130 it's have been fix in the 1.13.8 release 
https://github.com/hipay/hipay-fullservice-sdk-magento2/commit/d0eaec52d1aab18a60c055d75843fa0f514c4058

**Comment by legithubdeaymeric** [comment]
Yes it's fixed ;-)
