### ISSUE TITLE
Compilation hipay/hipay-fullservice-sdk-magento2 version 1.14.0 is ko

### ISSUE THREAD

**Issue by khnaim** [hipay/hipay-fullservice-sdk-magento2#146]
Hello,

I'm writing to you to report a bug when deploying module 'hipay/hipay-fullservice-sdk-magento2 version 1.14.0' on a Magento commerce ver. 2.4.3-p1 .

I have this message during 'bin/magento setup:di:compile':

**Repositories code generation... 1/9 [===>------------------------] 11% 1 sec 138.0 MiB
Fatal error: Access level to HiPay\FullserviceMagento\Logger\Logger::DEBUG_KEYS_MASK must be public (as in class Magento\Payment\Model\Method\Logger) in /app/vendor/hipay/hipay-fullservice-sdk-magento2/Logger/Logger.php on line 0**

Could you please look at this point?

Thanks in advance

**Comment by legithubdeaymeric** [comment]
Thanks !

Fixed in 1.14.1.
