### ISSUE TITLE
Bad constantes in di.xml

### ISSUE THREAD

**Issue by AgenceTBD** [hipay/hipay-fullservice-sdk-magento2#147]
Updating module via composer, last version 1.14.1 have bad constant defined  in the di.xml file.

This is the list : 
vendor/hipay/hipay-fullservice-sdk-magento2/etc/frontend/di.xml:34: <item name="hipay_mbway_hosted_fields" xsi:type="const">HiPay\FullserviceMagento\Model\Method\MbwayHostedFields::HIPAY_METHOD_CODE</item>
vendor/hipay/hipay-fullservice-sdk-magento2/etc/frontend/di.xml:108: <item name="hipay_mbway_hosted_fields" xsi:type="const">HiPay\FullserviceMagento\Model\Method\MbwayHostedFields::HIPAY_METHOD_CODE</item>
vendor/hipay/hipay-fullservice-sdk-magento2/etc/frontend/di.xml:34: <item name="hipay_multibanco_hosted_fields" xsi:type="const">HiPay\FullserviceMagento\Model\Method\MultibancoHostedFields::HIPAY_METHOD_CODE</item>
vendor/hipay/hipay-fullservice-sdk-magento2/etc/frontend/di.xml:127: <item name="hipay_multibanco_hosted_fields" xsi:type="const">HiPay\FullserviceMagento\Model\Method\MultibancoHostedFields::HIPAY_METHOD_CODE</item>

Classes MbwayHostedFields and MultibancoHostedFields does not exist.

I make a PR

**Comment by legithubdeaymeric** [comment]
Hi @AgenceTBD 

I don't understand:

https://github.com/hipay/hipay-fullservice-sdk-magento2/blob/master/Model/Method/MultibancoHostedFields.php

**Comment by AgenceTBD** [comment]
Okay... I see the miss...
Sorry for the issues, when getting update we have all files ok, but sending them over client repository the were missing.
My bad, thans for your return. I close them.
