### ISSUE TITLE
Notification on BO

### ISSUE THREAD

**Issue by brmor-mistermenuiserie** [hipay/hipay-fullservice-sdk-magento2#155]
Hello 

We have an error on our BO due to notification from your module.

![image](https://user-images.githubusercontent.com/103111614/212855757-baed8e20-8333-4949-bf6a-03723824f303.png)

Please can you fix this ?

**Comment by legithubdeaymeric** [comment]
https://github.com/hipay/hipay-fullservice-sdk-magento2/releases/tag/1.17.0
