### ISSUE TITLE
Impossible d'installer la dernière version (1.21) avec Magento 2.4.6-p2

### ISSUE THREAD

**Issue by toniodlab** [hipay/hipay-fullservice-sdk-magento2#160]
Bonjour,

J'ai un site internet en fonctionnement, mis à jour avec Magento 2.4.6-p2 le mois dernier.

J'ai beaucoup d'erreurs dans les logs et je souhaiterai mettre à jour le module HiPay 1.20 > 1.21

La commande `composer require hipay/hipay-fullservice-sdk-magento2:1.21` me retourne l'erreur suivante : 

  Problem 1
    - hipay/hipay-fullservice-sdk-php 2.15.0 requires ramsey/uuid ^3.9.7 -> found ramsey/uuid[3.9.7] but these were not loaded, likely because it conflicts with another require.
    - hipay/hipay-fullservice-sdk-magento2 1.21.0 requires hipay/hipay-fullservice-sdk-php ^2.15.0 -> satisfiable by hipay/hipay-fullservice-sdk-php[2.15.0].
    - Root composer.json requires hipay/hipay-fullservice-sdk-magento2 ^1.21 -> satisfiable by hipay/hipay-fullservice-sdk-magento2[1.21.0].

La commande  `composer require ramsey/uuid:3.9.7` me renvoie le message suivant : 

Problem 1
    - Root composer.json requires ramsey/uuid 3.9.7, found ramsey/uuid[3.9.7] but these were not loaded, likely because it conflicts with another require.
  Problem 2
    - magento/product-community-edition 2.4.6-p2 requires ramsey/uuid ^4.2 -> found ramsey/uuid[4.2.0, ..., 4.7.4] but it conflicts with your root composer.json require (3.9.7).
  Problem 3
    - allure-framework/allure-php-commons v2.3.1 requires ramsey/uuid ^3 || ^4 -> found ramsey/uuid[3.0.0, ..., 3.9.7, 4.0.0, ..., 4.7.4] but these were not loaded, likely because it confli
    - allure-framework/allure-phpunit v2.1.0 requires allure-framework/allure-php-commons ^2 -> satisfiable by allure-framework/allure-php-commons[v2.3.1].
    - allure-framework/allure-phpunit is locked to version v2.1.0 and an update of this package was not requested.

Avez-vous une idée de comment faire pour mettre à jour s'il vous plait ?

**Comment by JBaptisteLvt** [comment]
Bonjour,
Le souci de dépendance a été remonté sur notre SDK PHP, et est en cours de traitement. Nous allons publier des correctifs prochainement pour permettre ces montées de version. Nous n'avons pas de solution de contournement pour le moment, mais nous faisons au plus vite pour débloquer la situation.

**Comment by JBaptisteLvt** [comment]
Bonjour ! 
Le souci a été réglé dans la version 2.15.1 de notre SDK PHP. La version de Composer étant avec un ^, vous devriez pouvoir retenter l'installation telle quelle, et Composer devrait prendre la bonne version du SDK.

**Comment by JBaptisteLvt** [comment]
Bonjour !
Le souci a été définitivement corrigé avec la version 1.22.0 du module :)
