### ISSUE TITLE
Order cancel create two reservations on inventory_reservation table with MSI

### ISSUE THREAD

**Issue by syno-bgt** [hipay/hipay-fullservice-sdk-magento2#161]
Hi,

I saw the issue when i had difference between qty and salable_qty on my product

To reproduce the issue, follow these steps : 
- Create an order with hipay creditcard payment (for example) and 3DS but do not valid the order. Just close your page when you are on the bank page. 
- Wait the cron cancel the order (task hipay_clean_pending_orders)
- Go to inventory_reservation and filter on your order. You saw two line for the same item. 

To have a temporary fix, i just comment the line `$order->cancel();` on the Cron/CleanPendingOrders.php file.

It is not a correct fix, it causes other issues but not important on my side. 

Thank you.

**Comment by JBaptisteLvt** [comment]
Hello @syno-bgt !

I did kind of reproduce what you are saying, except the lines in inventory_reservation are cancelling each other : one has a positive quantity, and the other the negative quantity. I think this is magento's way to track reservation history.
In our test environment, the qty and salable_qty are equal after order cancellation.

HiPay does not tinker directly with quantities or stock, we use Magento's functions to cancel or update orders. Maybe another module is interfering with this function ?

**Comment by stormwind85** [comment]
Hi @syno-bgt 

Sorry for not responding to you sooner.

But this issue is related to this [closed one](https://github.com/hipay/hipay-fullservice-sdk-magento2/issues/163)

We did a fix on our latest version 1.22.3
I hope it will resolve your problem with our new version.

Now, I will close this ticket to avoid duplicate issues. Thanks again !
