### ISSUE TITLE
Restore on cart and notification Enable incompatibility

### ISSUE THREAD

**Issue by brmor-mistermenuiserie** [hipay/hipay-fullservice-sdk-magento2#162]
When notification cron is enable and restore on cart also, old cart is automatically restored.
Due to pending_payment status on last order.

**Comment by brmor-mistermenuiserie** [comment]
Fix with this patch
`--- Observer/RestoreBasketObserver.php	2023-11-20 07:53:41.142399962 +0100
+++ Observer/RestoreBasketObserver.php	2023-11-20 07:49:11.926877054 +0100
@@ -5,6 +5,7 @@
 use Magento\Framework\Event\ObserverInterface;
 use Magento\Framework\Event\Observer as EventObserver;
 use Magento\Checkout\Model\Session;
+use HiPay\FullserviceMagento\Model\Config;
 
 class RestoreBasketObserver implements ObserverInterface
 {
@@ -14,9 +15,13 @@
     private $checkoutSession;
 
     public function __construct(
-        Session $checkoutSession
+        Session $checkoutSession,
+		Config $hipayConfig
     ) {
         $this->checkoutSession = $checkoutSession;
+		$storeId = $this->checkoutSession->getQuote()->getStore()->getStoreId();
+		$this->hipayConfig = $hipayConfig;
+		$this->hipayConfig->setStoreId($storeId);
     }
 
     public function execute(EventObserver $observer)
@@ -26,7 +31,8 @@
 
         if (
             $lastRealOrder->getPayment()
-            && $lastRealOrder->getPayment()->getMethodInstance()->getConfigData('restore_cart_on_back')
+			&& $lastRealOrder->getPayment()->getMethodInstance()->getConfigData('restore_cart_on_back')
+			&& !$this->hipayConfig->isNotificationCronActive()
             && $lastRealOrder->getData('state') === 'pending_payment'
             && $lastRealOrder->getData('status') === 'pending_payment'
         ) {
`

**Comment by stormwind85** [comment]
Hi @brmor-mistermenuiserie 

Sorry for the late !

We will fix it as soon as possible !

Thanks also for your code suggestion 👍

**Comment by stormwind85** [comment]
Hi @brmor-mistermenuiserie 

Your patch has been integrated into our codebase on version 1.22.3

Be aware if you enable the cron notification option, the restore cart option is no longer available !

**Comment by stormwind85** [comment]
I close this issue because it has been fixed in our latest version
