### ISSUE TITLE
SDD payment 

### ISSUE THREAD

**Issue by YoanSamuel** [hipay/hipay-fullservice-sdk-magento2#164]
I have an error during my test when i try to process order. You use Zend Library who is depreciated. Here a fix with Laminas Library

**Comment by YoanSamuel** [comment]
--- a/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Method/Sdd.php	2024-04-11 14:08:52
+++ b/vendor/hipay/hipay-fullservice-sdk-magento2/Model/Method/Sdd.php	2024-04-11 13:47:49
@@ -119,10 +119,10 @@
         }

         // Instantiate validators for the model
-        $validatorIban = new \Zend\Validator\Iban(
+        $validatorIban = new \Laminas\Validator\Iban(
             array('country_code' => $order->getBillingAddress()->getCountryId())
         );
-        $validatorEmpty = new \Zend\Validator\NotEmpty();
+        $validatorEmpty = new \Laminas\Validator\NotEmpty();

         if (!$validatorIban->isValid($info->getAdditionalInformation('sdd_iban'))) {
             $errorMsg = __('Iban is not correct, please enter a valid Iban.');

**Comment by stormwind85** [comment]
Hi @YoanSamuel !

It has has been patched in the latest release [1.26.0](https://github.com/hipay/hipay-fullservice-sdk-magento2/releases/tag/1.26.0)

I close this issue accordingly.
