### ISSUE TITLE
Namespace errors ?

### ISSUE THREAD

**Issue by Dam62** [hipay/hipay-fullservice-sdk-magento2#68]
Hello ! 

We encountered errors during DI generation in production mode.
It seems that the errors come from  the namespace of two classes : 

https://github.com/hipay/hipay-fullservice-sdk-magento2/blob/master/src/Model/Method/Sisal.php
https://github.com/hipay/hipay-fullservice-sdk-magento2/blob/master/src/Model/Method/QiwiWallet.php

You can see that the namespace begins by "Hipay" instead of "HiPay", which apparently cause a lot of troubles in production mode.

Thanks in advance.

**Comment by jprotin** [comment]
Hello !
We check it and we return to you quickly.
Thank you.

**Comment by Dam62** [comment]
Thanks a lot for your answer.

There's also this class : https://github.com/hipay/hipay-fullservice-sdk-magento2/blob/master/src/Test/Unit/Model/CcConfigProviderTest.php

I think, the real namespace is HiPay\FullserviceMagento\Test\Unit\Model instead of HiPay\Fullservice\Test\Unit\Model ?

**Comment by jprotin** [comment]
Exact, we fix it very quicklly.

**Comment by jprotin** [comment]
https://github.com/hipay/hipay-fullservice-sdk-magento2/releases/tag/1.0.3

New release 1.0.3

If you find other bugs, please feel free to contribute to the project.
https://github.com/hipay/hipay-fullservice-sdk-magento2/blob/master/CONTRIBUTING.md 

Thank you !

Johan

**Comment by Dam62** [comment]
Hello ! 

Thanks a lot for your fixes !

Damien
