### ISSUE TITLE
Script Error with Hipay

### ISSUE THREAD

**Issue by damien-synolia** [hipay/hipay-fullservice-sdk-magento2#93]
Hello Hipay Guys !

I have another problem with your module. In file "hipay-fullservice-sdk-magento2/src/view/frontend/templates/fingerprint/fingerprint_js.phtml", you do this : 

`<script src="<?php echo $block->getJsSrc();?>" type="text/javascript" charset="utf-8" />`

But <script> tag do not allowed autoclosing. You should have : 

`<script src="<?php echo $block->getJsSrc();?>" type="text/javascript" charset="utf-8"></script>`

**Comment by legithubdeaymeric** [comment]
Thanks for your feedback.
